// Importações
import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/layout/navbar/NavBar";


// Metadados da aplicação
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


// Layout principal da aplicação
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="pt-BR">
            <body>
                <NavBar />
                {children}
            </body>
        </html>
    );
}
